export const hydratable = {
  artwork_url: "https://i1.sndcdn.com/artworks-CQla57R6PT2X-0-large.jpg",
  caption: null,
  commentable: true,
  comment_count: 5202,
  created_at: "2022-11-04T06:31:56Z",
  description: null,
  downloadable: false,
  download_count: 0,
  duration: 239386,
  full_duration: 239386,
  embeddable_by: "all",
  genre: "Rap",
  has_downloads_left: false,
  id: 1376227570,
  kind: "track",
  label_name: "OVO / Republic Records",
  last_modified: "2022-11-11T04:07:36Z",
  license: "all-rights-reserved",
  likes_count: 166904,
  permalink: "drake-21-savage-rich-flex",
  permalink_url:
    "https://soundcloud.com/octobersveryown/drake-21-savage-rich-flex",
  playback_count: 7476566,
  public: true,
  publisher_metadata: {
    id: 1376227570,
    urn: "soundcloud:tracks:1376227570",
    artist: "Drake, 21 Savage",
    album_title: "Her Loss",
    contains_music: true,
    upc_or_ean: "00602448926180",
    isrc: "USUG12208598",
    explicit: true,
    p_line:
      "℗ 2022 OVO, under exclusive license to Republic Records, a division of UMG Recordings, Inc",
    p_line_for_display:
      "℗ 2022 OVO, under exclusive license to Republic Records, a division of UMG Recordings, Inc",
    c_line:
      "© 2022 OVO, under exclusive license to Republic Records, a division of UMG Recordings, Inc",
    c_line_for_display:
      "© 2022 OVO, under exclusive license to Republic Records, a division of UMG Recordings, Inc",
    release_title: "Drake, 21 Savage - Rich Flex",
  },
  purchase_title: null,
  purchase_url: null,
  release_date: "2022-11-04T00:00:00Z",
  reposts_count: 2510,
  secret_token: null,
  sharing: "public",
  state: "finished",
  streamable: true,
  tag_list: "",
  title: "Drake, 21 Savage - Rich Flex",
  track_format: "single-track",
  uri: "https://api.soundcloud.com/tracks/1376227570",
  urn: "soundcloud:tracks:1376227570",
  user_id: 1078461,
  visuals: null,
  waveform_url: "https://wave.sndcdn.com/4ufacd02y5DN_m.json",
  display_date: "2022-11-04T04:00:00Z",
  media: {
    transcodings: [
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1376227570/dfef7275-0387-48f0-8b0d-b4e3308c1882/stream/hls",
        preset: "mp3_1_0",
        duration: 239386,
        snipped: false,
        format: { protocol: "hls", mime_type: "audio/mpeg" },
        quality: "sq",
      },
      {
        url: "https://api-v2.soundcloud.com/media/soundcloud:tracks:1376227570/d6ae2385-277c-4d50-a956-d086249971fa/stream/hls",
        preset: "opus_0_0",
        duration: 239366,
        snipped: false,
        format: {
          protocol: "hls",
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: "sq",
      },
    ],
  },
  station_urn: "soundcloud:system-playlists:track-stations:1376227570",
  station_permalink: "track-stations:1376227570",
  track_authorization:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IiIsInJpZCI6Ijc4MGQwNWU1LTFhMzItNDRmNy04ZjZmLTk0Mzk2NjBiMDJkMiIsImlhdCI6MTY3MDkwNjUxMn0.wrVUgDoj2wNuJ8ZnTRR_mCvcdw9R0eE5aHTC7iaNgdg",
  monetization_model: "AD_SUPPORTED",
  policy: "MONETIZE",
  user: {
    avatar_url: "https://i1.sndcdn.com/avatars-000111004820-tzrvo1-large.jpg",
    city: "Toronto",
    comments_count: 0,
    country_code: "CA",
    created_at: "2010-05-25T23:25:25Z",
    creator_subscriptions: [{ product: { id: "creator-pro-unlimited" } }],
    creator_subscription: {
      product: { id: "creator-pro-unlimited" },
    },
    description: "",
    followers_count: 3010523,
    followings_count: 9,
    first_name: "October's",
    full_name: "October's Very Own",
    groups_count: 0,
    id: 1078461,
    kind: "user",
    last_modified: "2022-06-21T21:57:48Z",
    last_name: "Very Own",
    likes_count: 7,
    playlist_likes_count: 1,
    permalink: "octobersveryown",
    permalink_url: "https://soundcloud.com/octobersveryown",
    playlist_count: 28,
    reposts_count: null,
    track_count: 473,
    uri: "https://api.soundcloud.com/users/1078461",
    urn: "soundcloud:users:1078461",
    username: "octobersveryown",
    verified: true,
    visuals: null,
    badges: { pro: false, pro_unlimited: true, verified: true },
    station_urn: "soundcloud:system-playlists:artist-stations:1078461",
    station_permalink: "artist-stations:1078461",
  },
};
